version: '3'

services:
  api:
    container_name: api
    env_file:
      - .env
    build: .
    command: npm run start:dev
    ports:
      - ${API_PORT}:${API_PORT}
    volumes:
      - .:/usr/app
    environment:
      DB_HOST: database
      DB_PORT: 3306
    networks:
      - crud-veiculos

  database:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - './.mysql-data/db:/var/lib/mysql'
    restart: always
    ports:
      - ${DB_PORT}:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    networks:
      - crud-veiculos

networks:
  crud-veiculos:
    driver: bridge
